---

- hosts: all
  sudo: yes
  tasks: 
  
  - name: copy script of formating and mounting the disk
    copy:
      src: ./format-mount.sh
      dest: /opt/format-mount.sh
      owner: root
      group: root
      mode:  777
      
  - name: running the script of formating and mounting the disk
    shell: bash -x /opt/format-mount.sh

  - name: REDHAT SATELLITE REGISTRATION STEPS AT CLIENt SIDE
    command: subscription-manager register --username=satadmin --password=admin --environment=PROD/CV-RHEL7 -- baseurl=https://sngp1vlcprhs01.dapac.aspa.smbc.local/pulp/repos/; subscription-manager attach
  
  - name: Run precheck, sysbackup scripts and apply patch to the server
    yum: name=* state=latest



